const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(languages);
const firstElement = languages[0];
console.log('the first element is ' + firstElement);
const thirdElement = languages[2];
console.log('the third element is ' + thirdElement);
const length = languages.length;
console.log('the length of the array is ' + length);
const lastElement = languages[length - 1];
console.log('the last element is ' + lastElement);
